---
sidebar: sidebar 
permalink: get-started/software-updates-faq.html 
keywords: ontap update faq, ontap update frequently asked questions, software updates faq, software updates frequently asked questions, troubleshooting 
summary: 查看有关BlueXP  软件更新的常见问题解答。 
---
= BlueXP  软件更新的常见问题解答
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想了解有关BlueXP  软件更新的更多信息或需要任何故障排除帮助、可以查看这些问题以获得快速解答。

*什么是BlueXP  软件更新URL？*

对于URL、在浏览器中输入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] 以访问BlueXP  控制台。

*使用BlueXP  软件更新是否需要许可证？*

不需要NetApp许可证文件(NLF)。

*为什么在更新集群的ONTAP版本后仍无法在历史记录选项卡中查看此集群？*

此集群需要2到3小时才能显示在历史记录选项卡中。更新集群的ONTAP版本后、将生成AutoSupport。处理AutoSupport数据并反映最新版本的ONTAP需要2到3个小时。

*为什么在更新集群的ONTAP版本后，软件更新信息板中仍会显示旧版本的ONTAP？*

此集群需要2到3小时才能显示在历史记录选项卡中。更新集群的ONTAP版本后、将生成AutoSupport。处理AutoSupport数据并反映最新版本的ONTAP需要2到3个小时。

*为什么我看到不同的屏幕显示不同的更新？*

这是由于当前ONTAP版本以及BlueXP  Connector不适用于集群。BlueXP  Connector在BlueXP  中执行ONTAP更新、不需要您退出BlueXP  进行更新。如果您没有BlueXP  Connector、则会重定向到System Manager、并需要重新输入ONTAP集群凭据。有关不同ONTAP版本的ONTAP更新过程的信息，请参见 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["支持的 ONTAP 系统"]。

*发现集群需要什么？*

要对所需集群执行ONTAP更新、您需要ONTAP集群IP和用于连接到集群的管理员凭据。在集群发现过程中、您需要提供这些详细信息、才能自动执行ONTAP更新。

您还需要拥有以下访问角色之一：组织管理员、文件夹或项目管理员或存储管理员。
